### ISSUE TITLE
vgg_16/conv1/conv1_1/weights does not exist ?

### ISSUE THREAD

**Issue by gotope** [warmspringwinds/tensorflow_notes#1]
hello, follow your tutorial encounter a problem, which is ,  simple_classification_segmentation.ipynb

> Below you can see an example of Image Classification. We preprocess the input image by resizing it while preserving the aspect ratio and crop the central part. The size of the crop is equal to the size of images that the network was trained on.
> 
> %matplotlib inline

the trace,
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-dc28a00b8ac5> in <module>()
     54         logits, _ = vgg.vgg_16(processed_images,
     55                                num_classes=1000,
---> 56                                is_training=False)
     57 
     58     # In order to get probabilities we apply softmax on the output.

/home/opuser/models/slim/nets/vgg.py in vgg_16(inputs, num_classes, is_training, dropout_keep_prob, spatial_squeeze, scope)
    152     with slim.arg_scope([slim.conv2d, slim.fully_connected, slim.max_pool2d],
    153                         outputs_collections=end_points_collection):
--> 154       net = slim.repeat(inputs, 2, slim.conv2d, 64, [3, 3], scope='conv1')
    155       net = slim.max_pool2d(net, [2, 2], scope='pool1')
    156       net = slim.repeat(net, 2, slim.conv2d, 128, [3, 3], scope='conv2')

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.pyc in repeat(inputs, repetitions, layer, *args, **kwargs)
    958     for i in range(repetitions):
    959       kwargs['scope'] = scope + '_' + str(i+1)
--> 960       outputs = layer(outputs, *args, **kwargs)
    961     return outputs
    962 

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    169       current_args = current_scope[key_func].copy()
    170       current_args.update(kwargs)
--> 171     return func(*args, **current_args)
    172   _add_op(func)
    173   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.pyc in convolution2d(inputs, num_outputs, kernel_size, stride, padding, rate, activation_fn, normalizer_fn, normalizer_params, weights_initializer, weights_regularizer, biases_initializer, biases_regularizer, reuse, variables_collections, outputs_collections, trainable, scope)
    405                                        regularizer=weights_regularizer,
    406                                        collections=weights_collections,
--> 407                                        trainable=trainable)
    408     if rate > 1:
    409       outputs = nn.atrous_conv2d(inputs, weights, rate, padding=padding)

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    169       current_args = current_scope[key_func].copy()
    170       current_args.update(kwargs)
--> 171     return func(*args, **current_args)
    172   _add_op(func)
    173   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.pyc in model_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device)
    264                   initializer=initializer, regularizer=regularizer,
    265                   trainable=trainable, collections=collections,
--> 266                   caching_device=caching_device, device=device)
    267 
    268 

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.pyc in func_with_args(*args, **kwargs)
    169       current_args = current_scope[key_func].copy()
    170       current_args.update(kwargs)
--> 171     return func(*args, **current_args)
    172   _add_op(func)
    173   setattr(func_with_args, '_key_op', _key_op(func))

/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/variables.pyc in variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, device)
    228                                        trainable=trainable,
    229                                        collections=collections,
--> 230                                        caching_device=caching_device)
    231 
    232 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    828       collections=collections, caching_device=caching_device,
    829       partitioner=partitioner, validate_shape=validate_shape,
--> 830       custom_getter=custom_getter)
    831 
    832 

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    671           collections=collections, caching_device=caching_device,
    672           partitioner=partitioner, validate_shape=validate_shape,
--> 673           custom_getter=custom_getter)
    674 
    675   def _get_partitioned_variable(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, custom_getter)
    215           reuse=reuse, trainable=trainable, collections=collections,
    216           caching_device=caching_device, partitioner=partitioner,
--> 217           validate_shape=validate_shape)
    218 
    219   def _get_partitioned_variable(

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape)
    200           initializer=initializer, regularizer=regularizer, reuse=reuse,
    201           trainable=trainable, collections=collections,
--> 202           caching_device=caching_device, validate_shape=validate_shape)
    203 
    204     if custom_getter is not None:

/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.pyc in _get_single_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, validate_shape)
    510       raise ValueError("Variable %s does not exist, or was not created with "
    511                        "tf.get_variable(). Did you mean to set reuse=None in "
--> 512                        "VarScope?" % name)
    513     if not shape.is_fully_defined() and not initializing_from_value:
    514       raise ValueError("Shape of a new variable (%s) must be fully defined, "

ValueError: Variable vgg_16/conv1/conv1_1/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by warmspringwinds** [comment]
Hi.

Did you download the vgg checkpoint file?

**Comment by gotope** [comment]
@warmspringwinds    thanks. 

I have upgrade the tensoflow and it fixed the issue.
