### ISSUE TITLE
NameError: name 'processed_probabilities' is not defined

### ISSUE THREAD

**Issue by FrantisekVidensky** [warmspringwinds/tensorflow_notes#3]
Hi,
I came across your article about "Image Segmentation with Tensorflow using CNNs and Conditional Random Fields"  and I tried to follow him. But in last section (Conditional Random Field post-processing) I have error in line: 
`softmax = processed_probabilities.transpose((2, 0, 1)) `
because variable processed_probabilities is nowhere defined. I tried to correct that mistake myself, but I failed.
Could you please help with this error?

`NameError: name 'processed_probabilities' is not defined`

Thanks you.

**Comment by warmspringwinds** [comment]
Hi, @FrantisekVidensky 

Yeah, seems like I missed something.
I am currently away from my main pc, where I have ran all experiments, but
it seems like making this change in my current code might help:

```
softmax = final_probabilities.squeeze()

softmax = softmax.transpose((2, 0, 1))
```

Let me know if it helps

**Comment by FrantisekVidensky** [comment]
Hi, @warmspringwinds 

variable "processed_probabilities" is also needed for computed unary.

`unary = softmax_to_unary(processed_probabilities)
unary = np.ascontiguousarray(unary)`

When you are not away from your main pc, can you check it please?

**Comment by warmspringwinds** [comment]
@FrantisekVidensky 

Sure, I will.

So far, try replacing it with:

```
unary = softmax_to_unary(softmax) unary = np.ascontiguousarray(unary)
```

plus my changes above.

I will explore it more a little bit later.

**Comment by FrantisekVidensky** [comment]
It works!
Thank you very much!
